global:
  scrape_interval: 1m
  
scrape_configs: 
  - job_name: 'auth-service'
    metrics_path: /metrics
    static_configs: 
        - targets: ['auth-service:8080']
          
  - job_name: 'catalog-service'
    metrics_path: /metrics
    static_configs: 
        - targets: ['catalog-service:8080']
          
  - job_name: 'order-service'
    metrics_path: /metrics
    static_configs: 
        - targets: ['order-service:8080']
          
  - job_name: 'payment-service'
    metrics_path: /metrics
    static_configs: 
        - targets: ['payment-service:8080']