namespace Auth.Application.DTOs
{
    /// <summary>
    /// Authentication token generated by JWT.
    /// </summary>
    public class AuthToken
    {
        /// <summary>
        /// Short-live token.
        /// </summary>
        public required string AccessToken { get; set; }

        /// <summary>
        /// Expiration time of the access token.
        /// </summary>
        public required DateTime ExpiresAt { get; set; }
    }
}