name: Auth Service CI

on:
  push:
    branches:
      - main
      - develop
    paths:
      - 'services/auth/**'
  pull_request:
    branches:
      - main
      - develop
    paths:
      - 'services/auth/**'

jobs:
  build:
    uses: cardosakv/mercibus/.github/workflows/base-build.yml@develop
    with:
      service: auth
  
  test:
    uses: cardosakv/mercibus/.github/workflows/base-test.yml@develop
    with:
      service: auth
  
  analyze:
    uses: cardosakv/mercibus/.github/workflows/base-sonarqube.yml@develop
    with:
      service: auth
      project_key: mercibus_auth
      project_dll: Auth
      sonar_token: ${{ secrets.SONAR_TOKEN_AUTH }}
  
  dockerize:
    uses: cardosakv/mercibus/.github/workflows/base-dockerize.yml@develop
    with:
      service: auth
      image_name: mercibus_auth