name: Base SonarCloud Analysis

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
      project_key:
        required: true
        type: string
      project_dll:
        required: true
        type: string
      sonar_token:
        required: true
        type: string

jobs:
  analyze:
    runs-on: windows-latest

    defaults:
      run:
        working-directory: ./services/${{ inputs.service }}/

    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      - name: Begin SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ inputs.sonar_token }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin `
            /k:"${{ inputs.project_key }}" `
            /o:"cardosakv" `
            /d:sonar.token="${{ inputs.sonar_token }}" `
            /d:sonar.host.url="https://sonarcloud.io" `
            /d:"sonar.cs.opencover.reportsPaths=**/coverage.opencover.xml" `
            /d:"sonar.coverage.exclusions=**/${{ inputs.project_dll }}.Infrastructure/**/*.cs,**/${{ inputs.project_dll }}.Domain/**/*.cs,**/${{ inputs.project_dll }}.Api/Program.cs,**/${{ inputs.project_dll }}.Api/Middlewares/**/*.cs,**/${{ inputs.project_dll }}.Application/Common/**/*.cs,**/${{ inputs.project_dll }}.Validators/**/*.cs"

      - name: Restore and build
        shell: powershell
        run: |
          dotnet restore
          dotnet build --no-restore --configuration Release

      - name: Install Coverlet CLI
        shell: powershell
        run: dotnet tool install --global coverlet.console

      - name: Run tests with OpenCover coverage
        shell: powershell
        run: |
          coverlet ./${{ inputs.project_dll }}.Tests/bin/Release/net8.0/${{ inputs.project_dll }}.Tests.dll `
            --target "dotnet" `
            --targetargs "test ./${{ inputs.project_dll }}.Tests/${{ inputs.project_dll }}.Tests.csproj --no-build --configuration Release" `
            --format opencover `
            --output "./TestResults/coverage.opencover.xml"

      - name: List coverage files (debug)
        shell: powershell
        run: Get-ChildItem -Recurse -Filter "coverage.opencover.xml"

      - name: End SonarCloud analysis
        env:
          SONAR_TOKEN: ${{ inputs.sonar_token }}
        shell: powershell
        run: .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ inputs.sonar_token }}"