name: Base Test

on:
  workflow_call:
    inputs:
      service:
        required: true
        type: string
    secrets:
      jwt_key:
        required: false
      email_server:
        required: false
      email_port:
        required: false
      email_sender:
        required: false
      email_username:
        required: false
      email_password:
        required: false
      redirect_email_confirm_success:
        required: false
      redirect_email_confirm_fail:
        required: false
      redirect_password_reset:
        required: false

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/${{ inputs.service }}/

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-docker-action@v4.3.0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal
        env:
          Jwt__Key: ${{ secrets.jwt_key }}
          Email__Server: ${{ secrets.email_server }}
          Email__Port: ${{ secrets.email_port }}
          Email__Sender: ${{ secrets.email_sender }}
          Email__Username: ${{ secrets.email_username }}
          Email__Password: ${{ secrets.email_password }}
          RedirectUrl__EmailConfirmSuccess: ${{ secrets.redirect_email_confirm_success }}
          RedirectUrl__EmailConfirmFail: ${{ secrets.redirect_email_confirm_fail }}
          RedirectUrl__PasswordReset: ${{ secrets.redirect_password_reset }}